#controllers:
#    resource: ../src/Controller/RandomController.php
#    type: annotation
#    prefix: /test

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
